### ISSUE TITLE
Not working with Elixir 5

### ISSUE THREAD

**Issue by Grawl** [tureki/laravel-elixir-postcss#6]
Trying to configure it like this:

``` js
elixir(mix=> {
    mix.postcss('*.css', {
        srcDir: production ? 'public' : 'public/build',
        plugins: [
            require('postcss-short')
        ]
    })
})
```

But it's not working at all:

```
    mix.postcss('*.css', {
        ^

TypeError: mix.postcss is not a function
    at mix (/Users/grawl/Sites/laravel-project/gulpfile.js:33:6)
    at Elixir (/Users/grawl/Sites/laravel-project/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/Users/grawl/Sites/laravel-project/gulpfile.js:32:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

Process finished with exit code 1
```

**Comment by iantearle** [comment]
I don't get the above error but I'm ~~not getting~~ any output when gulp is run.

```
[12:59:37] Starting 'default'...
[12:59:37] Starting 'postcss'...
[12:59:38] Finished 'default' after 978 ms
[12:59:38] Finished 'postcss' after 985 ms
```

Sorry, scrub that, didn't realise you needed to put the CSS in postcss folder...

**Comment by tureki** [comment]
Hi @Grawl ,

I don't get error message when I try your configure in my Laravel 5.2 project ("laravel-elixir": "^5.0.0")

Do you have `require('laravel-elixir-postcss');` before you run `mix.postcss` ?

Thank your report 👍

**Comment by Grawl** [comment]
@tureki yes.

**Comment by tureki** [comment]
@Grawl  Can you show me your `gulpfile.js` and `package.json` ?

---

And try `srcDir: production ? 'public' : 'public/build'` change **srcDir** to **output**

**Comment by Grawl** [comment]
`gulpfile.js`

``` js
"use strict"
// Globals
var gulp = require('gulp')
var elixir = require('laravel-elixir')
var dotenv = require('dotenv')
var glob = require('glob')
// Locals
var env = dotenv.config()
// console.log('env', env)
// Tasks
elixir(mix=> {
    let browsersyncOptions = {
        injectChanges: true,
        proxy: env.APP_URL,
        open: false
    }
    if (env.BROWSERSYNC_PORT) {
        Object.assign(browsersyncOptions, {
            port: parseInt(env.BROWSERSYNC_PORT),
            ui: {
                port: parseInt(env.BROWSERSYNC_PORT) + 1
            }
        })
    }
    console.log('browsersyncOptions', browsersyncOptions)
    mix.browserSync(browsersyncOptions)
})
elixir(mix=> {
    mix.sass([
        '!_*',
        '*.{scss,sass}'
    ])
})
elixir(mix=> {
    // you have to restart this task to catch new or removed files
    mix.browserify(glob.sync('*.js', {cwd: 'resources/assets/js'}))
})
elixir(mix=> {
    mix.copy([
        'node_modules/font-awesome/fonts/*.*'
    ],
    'public/fonts/')
})
gulp.task('version', [], ()=> {
    return elixir(mix=> {
        mix.version('{css,js}/*.{css,js}')
    })
})
```

**Comment by tureki** [comment]
Try this

``` js
require('laravel-elixir-postcss');

elixir(mix=> {
    mix.postcss('*.css', {
        plugins: [
            require('postcss-short')
        ]
    })
})
```

**Comment by Grawl** [comment]
@tureki okay so I have to `require` it like this:

``` js
require('laravel-elixir-postcss')
```

not like this:

``` js
var postcss = require('laravel-elixir-postcss')
```

right?

It not works too, but at least without errors:

```
[13:45:54] Using gulpfile ~/Sites/laravel-project/gulpfile.js
[13:45:54] Starting 'postcss'...
[13:45:56] Finished 'postcss' after 1.74 s

Process finished with exit code 0
```

Config:

``` js
require('laravel-elixir-postcss')
elixir(mix=> {
    mix.postcss('post.css', {
        plugins: [
            require('postcss-short')
        ]
    })
})
```

I have no new files at `public/css` and existing `public/css/app.css` is not changed.

And I want to add PostCSS to a pipeline to process CSS coming from Sass, it is possible with Elixir?

**Comment by tureki** [comment]
@Grawl Yes, it possible with Elixir.

Have many ways you can do that.

For example:

``` js
var elixir = require('laravel-elixir');

require('laravel-elixir-postcss');

elixir(mix => {

  mix
    //output to resources/assets/postcss
    .sass('app.scss', elixir.config.assetsPath + '/postcss')
    //run postcss after sass compile
    .postcss('*.css', {
      plugins: [
        require('postcss-short')
      ]
    });

});
```

If you think this way is not good enough.

You can write custom plugin do whatever you want. ([extensions](https://laravel.com/docs/5.0/elixir#extensions))

ps: Confirm CSS file in `resources/assets/postcss` folder. [(see default options)](https://github.com/tureki/laravel-elixir-postcss#default-options)

**Comment by Grawl** [comment]
@tureki okay it's work now.

But I have an error:

```
PostCSS - Error
   - "/node_modules/font-awesome/scss/font-awesome.scss" is not in the SourceMap.
```

How can I fix that without turning off or breaking my SourceMaps?

**Comment by Grawl** [comment]
Okay looks like I fixed this by adding `srcDir: elixir.config.assetsPath + '/sass'` to PostCSS configuration (or broke something else) but I have not this SourceMaps error anymore.

Now I have this config:

``` js
"use strict"
// Globals
var gulp = require('gulp')
var elixir = require('laravel-elixir')
require('laravel-elixir-postcss')
elixir.config.css.autoprefix = false
elixir(mix=> {
    mix
        .sass(
            [
                '!_*',
                '*.{scss,sass}'
            ],
            elixir.config.assetsPath + '/postcss'
        )
        .postcss('*.css', {
            plugins: [
                require('postcss-short')
            ],
            srcDir: elixir.config.assetsPath + '/sass'
        }, 'public/css')
})
```

And it does nothing with PostCSS:

```
[16:51:38] Using gulpfile ~/Sites/laravel-project/gulpfile.js
[16:51:38] Starting 'default'...
[16:51:38] Starting 'sass'...

Fetching Sass Source Files...
   - !resources/assets/sass/_*/**/*
   - resources/assets/sass/*.{scss,sass}


Saving To...
   - resources/assets/postcss/app.css

[16:51:39] Finished 'default' after 1.83 s
[16:51:40] gulp-notify: [Laravel Elixir] Sass Compiled!
[16:51:40] Finished 'sass' after 2.52 s
[16:51:40] Starting 'postcss'...
[16:51:40] Finished 'postcss' after 83 ms

Process finished with exit code 0
```

And if I try to launch PostCSS task separately, I have the same: nothing.
Only Sass works for now.

**Comment by tureki** [comment]
@Grawl , 

The following is my modify:

``` js
"use strict"
// Globals
var gulp = require('gulp')
var elixir = require('laravel-elixir')
require('laravel-elixir-postcss')
elixir.config.css.autoprefix = false
elixir(mix=> {
    mix
        .sass(
            [
                '!_*',
                '*.{scss,sass}'
            ],
            elixir.config.assetsPath + '/postcss'
        )
        .postcss('*.css', {
            plugins: [
                require('postcss-short')
            ],
            output: 'public/css'
        })
})
```

Above setting step:
1. sass --> compile scss files in `elixir.config.assetsPath + '/sass'` folder
2. output css file to `elixir.config.assetsPath + '/postcss'`  after sass compile.
3. postcss ---> compile css files in `elixir.config.assetsPath + '/postcss'` folder.
4. output css file to `public/css`  after postcss compile.

**Comment by Grawl** [comment]
@tureki looks like it works.

But I have this error from https://github.com/tureki/laravel-elixir-postcss/issues/6#issuecomment-220898584 again

**Comment by tureki** [comment]
@Grawl ,

OK, I will add new options `sourcemap` in next version.

**Comment by tureki** [comment]
@Grawl , try [new release](https://github.com/tureki/laravel-elixir-postcss/releases) 👍 

``` js
mix.postcss('app.css', {
  sourcemaps: false // disable sourcemap
});
```

**Comment by Grawl** [comment]
@tureki but I don't want just to disable sourcemaps. I need them.

If I add [`{loadMaps: true}`](https://github.com/floridoo/gulp-sourcemaps#load-existing-source-maps) to [`index.js:36`](https://github.com/tureki/laravel-elixir-postcss/blob/master/index.js#L36) to get this:

``` diff
- .pipe(plugins.if(options.sourcemaps, plugins.sourcemaps.init())))
+ .pipe(plugins.if(options.sourcemaps, plugins.sourcemaps.init({loadMaps: true}))))
```

I got this:

```
[15:00:08] Starting 'default'...
[15:00:08] Starting 'browserSync'...
[15:00:08] Finished 'browserSync' after 634 μs
[15:00:08] Starting 'sass'...

Fetching Sass Source Files...
   - !resources/assets/sass/_*/**/*
   - resources/assets/sass/*.{scss,sass}


Saving To...
   - resources/assets/postcss/app.css

[15:00:09] Finished 'default' after 1.49 s
[15:00:11] gulp-notify: [Laravel Elixir] Sass Compiled!
[15:00:11] Finished 'sass' after 3.29 s
[15:00:11] Starting 'postcss'...

Process finished with exit code 0
```

I want to post-process CSS after Sass. With Source Maps.

**Comment by tureki** [comment]
@Grawl , You can do this:

``` js
elixir.config.sourcemaps = false; // disable elixir sass sourcemap

elixir(mix=> {
  mix
    .sass(...)
    .postcss('*.css', {
      ...
      sourcemaps: true // enable postcss sourcemap
    })
})
```

**Comment by Grawl** [comment]
@tureki okay now I got Source Maps from PostCSS but not from Sass. I want both :(
what the problem with `loadMaps` in your plugin?

**Comment by tureki** [comment]
Hi @Grawl , 

I think this plugin (latest version) is unable to meet your needs.

Because it just a simple plugin and design to the user just using PostCSS not both 😞 .

Of course, I will also think about how to fix this problem in next version.

Welcome PR. If you have interest extend this plugin 😄

**Comment by Grawl** [comment]
I understand. Laravel Elixir architecture cannot fit my needs, sadly. I think there is only one way: create new Elixir Extend Task and use raw Gulp task inside it to combine Sass with PostCSS.
