### ISSUE TITLE
Not working with Elixir v6

### ISSUE THREAD

**Issue by sgraewe** [tureki/laravel-elixir-postcss#8]
Hi, i tried to compile my postcss-file and got this error:

```
node:44743) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/Notification'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sgraewe/Code/Nerdlounge/node_modules/laravel-elixir-postcss/index.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by 7ammer** [comment]
Same here.
+1 for v6

**Comment by tureki** [comment]
Hi guys,

Elixir v6 isn't officially out yet.

I think it will be fixed after v6 release.

**Comment by marklj** [comment]
As a short term solution, you can just comment out the lines relating to notifications (index.js lines 5 and 41).

**Comment by DanielHudson** [comment]
In the mean time you could also use this fork...

`npm install https://github.com/Metrique/laravel-elixir-postcss.git --save-dev`

**Comment by tureki** [comment]
Thk @DanielHudson 👍 

The [PR](https://github.com/tureki/laravel-elixir-postcss/pull/9) have been merged 😄

Check [v0.4.0](https://github.com/tureki/laravel-elixir-postcss/releases/tag/v0.4.0) release.
